In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

# here ([1, 2, 3, 4, 5, 6, 7]) = ([-7,-6,-5,-4,-3,-2,-1])  
# here -3 is last 3rd number = 5. 

[5 6]


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

# here 1st input is start 2nd input is stop & 3rd is step
# here 1st is 1=2, 2nd is 5=2,3,4,5. and 3rd is 2= took element after every 2 step

[2 4]


In [7]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

# 1st input is row & 2nd input is column

[7 8 9]


In [11]:
#2D

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

# here 6, 7, 8, 9, 10 is in 2nd row = 1. then why it's took 0:2?? 

[[2 3 4]
 [7 8 9]]
